#!/bin/bash

# Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
# eDP-1 connected (normal left inverted right x axis y axis)
#	1366x768      60.02 +
# 1360x768      59.80    59.96  
# 1024x768      60.04    60.00  
# 960x720       60.00  

#
# Mupen is weird about fullscreen. You must also supply the right resolution or
# else it will run in a window :-P
# 

. $RETROCADE_OS_HOME/lib/lib.sh
read -r X Y <<< $(get_resolution)

ROM_BASE=~/RetrocadeOS/n64_roms

mupen64plus --fullscreen --resolution ${X}x${Y} --gfx mupen64plus-video-glide64mk2 $ROM_BASE/$1
